# This file is generated by rules_erlang via the erlang_config macro

load(
    "%{RULES_ERLANG_WORKSPACE}//private:erlang_build.bzl",
    "erlang_external",
)
load(
    "%{RULES_ERLANG_WORKSPACE}//tools:erlang_toolchain.bzl",
    "erlang_toolchain",
)

erlang_external(
    name = "otp-%{ERLANG_NAME}",
    erlang_home = "%{ERLANG_HOME}",
    erlang_version = "%{ERLANG_VERSION}",
)

erlang_toolchain(
    name = "erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    otp = ":otp-%{ERLANG_NAME}",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "//:erlang_external",
%{EXTRA_EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}",
%{EXTRA_TARGET_CONSTRAINTS}    ],
    toolchain = ":erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    toolchain_type = "%{RULES_ERLANG_WORKSPACE}//tools:toolchain_type",
    visibility = ["//visibility:public"],
)
