# This file is generated by rules_erlang via the erlang_config macro

load(
    "%{RULES_ERLANG_WORKSPACE}//private:erlang_build.bzl",
    "erlang_release_archive",
)
load(
    "%{RULES_ERLANG_WORKSPACE}//tools:erlang_toolchain.bzl",
    "erlang_toolchain",
)

# Extract a prebuilt, relocatable OTP release tarball (fetched via http_file)
# into the tree artifact + OtpInfo the toolchain consumes. No compilation.
erlang_release_archive(
    name = "otp-%{ERLANG_NAME}",
    tar = "%{PREBUILT_ARCHIVE_LABEL}",
    version = "%{ERLANG_VERSION}",
    visibility = ["//visibility:public"],
)

erlang_toolchain(
    name = "erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    otp = ":otp-%{ERLANG_NAME}",
    visibility = ["//visibility:public"],
)

# A prebuilt is architecture-specific, so exec/target constraints are mandatory
# (enforced in the module extension). The exec platform must declare
# //:erlang_prebuilt (mirroring how internal toolchains require //:erlang_internal).
toolchain(
    name = "toolchain_major",
    exec_compatible_with = [
        "//:erlang_prebuilt",
%{EXTRA_EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:erlang_%{ERLANG_MAJOR}",
%{EXTRA_TARGET_CONSTRAINTS}    ],
    toolchain = ":erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    toolchain_type = "%{RULES_ERLANG_WORKSPACE}//tools:toolchain_type",
    visibility = ["//visibility:public"],
)

alias(
    name = "toolchain",
    actual = "toolchain_major",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain_major_minor",
    exec_compatible_with = [
        "//:erlang_prebuilt",
%{EXTRA_EXEC_CONSTRAINTS}    ],
    target_compatible_with = [
        "//:erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}",
%{EXTRA_TARGET_CONSTRAINTS}    ],
    toolchain = ":erlang_%{ERLANG_MAJOR}_%{ERLANG_MINOR}_toolchain",
    toolchain_type = "%{RULES_ERLANG_WORKSPACE}//tools:toolchain_type",
    visibility = ["//visibility:public"],
)

alias(
    name = "toolchain2",
    actual = "toolchain_major_minor",
    visibility = ["//visibility:public"],
)
